extends: teaching_material
metadata:
  doc_type: master_lesson
  institution: UNIR
  link-citations: true
resource_path:
  - "/Users/juanjo/Library/CloudStorage/OneDrive-KALEIDAGEOGRAFIAS&MERCADOSSL/UNIR/Actualización de Contenidos/Ecosistema Digital y Tecnologías Disruptivas/Curso 2026/Tema 1"
