extends: research_article
cover_template: assets/templates/plantilla_pulse.docx
cover_mode: metadata
metadata:
  doc_type: long_article
  brand: Convercus
resource_path:
  - "/Users/juanjo/Library/CloudStorage/OneDrive-ConvercusGmbH/Convercus/Articles & Posts"
